services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - gestao-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao_spring_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_CLEAN_ON_STARTUP: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    ports:
      - "8081:8080"
    networks:
      - gestao-net

networks:
  gestao-net:
    name: gestao-net