-- Criar tabela members
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL
);

-- Criar tabela projects
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio DATE NOT NULL,
    data_real_termino DATE,
    orcamento_total NUMERIC(38,2) NOT NULL,
    previsao_termino DATE NOT NULL,
    descricao VARCHAR(255),
    gerente_id BIGINT,
    nome VARCHAR(255) NOT NULL,
    status VARCHAR(255) CHECK (status IN ('EM_ANALISE', 'ANALISE_REALIZADA', 'ANALISE_APROVADA', 'INICIADO', 'PLANEJADO', 'EM_ANDAMENTO', 'ENCERRADO', 'CANCELADO')),
    FOREIGN KEY (gerente_id) REFERENCES members(id)
);

-- Criar tabela project_membros
CREATE TABLE project_membros (
    project_id BIGINT NOT NULL,
    membros BIGINT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (membros) REFERENCES members(id)
);